version: '3.8'

networks:
  localdev:
    driver: bridge

volumes:
  elasticsearch:
    driver: local
  redis:
    driver: local

services:
  ### mariadb #############
  mariadb:
    restart: always
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - ${MARIADB_DATA_DIR}:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - localdev

  ### php-fpm #############
  php-fpm:
    restart: always
    image: sxbrsky/php-fpm:${PHP_VERSION}
    volumes:
      - ${CODE_PATH_HOST}:${CODE_PATH_CONTAINER}${CODE_PATH_CONTAINER_FLAG}
    expose:
      - 9000
    networks:
      - localdev

  ### nginx #############
  nginx:
    restart: always
    build:
      context: nginx/
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    volumes:
      - ${CODE_PATH_HOST}:${CODE_PATH_CONTAINER}${CODE_PATH_CONTAINER_FLAG}
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
    ports:
       - "${NGINX_HTTP_PORT}:80"
       - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - localdev

  ### phpMyAdmin #############
  phpmyadmin:
    restart: always
    build:
      context: phpmyadmin/
      args:
        PMA_VERSION: ${PMA_VERSION}
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - localdev

  ### redmine #############
  redmine:
    restart: always
    image: redmine:${REDMINE_VERSION}
    volumes:
      - ~/code:/projects:ro
      - ${REDMINE_PLUGINS_DIR}:/usr/src/redmine/plugins:ro
      - ${REDMINE_THEMES_DIR}:/usr/src/redmine/public/themes:ro
    environment:
      REDMINE_DB_MYSQL: ${REDMINE_DB_MYSQL}
      REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_DB_DATABASE: ${REDMINE_DB_DATABASE}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE}
    ports:
      - "${REDMINE_PORT}:3000"
    depends_on:
      - mariadb
    networks:
      - localdev

  ### redis #############
  redis:
    restart: always
    build:
      context: redis/
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - localdev

  ### elasticsearch #############
  elasticsearch:
    restart: always
    build:
      context: elasticsearch/
      args:
        ELASTICSEARCH_VERSION: ${ELASTICSEARCH_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    environment:
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTICSEARCH_CLUSTER_NAME: ${ELASTICSEARCH_CLUSTER_NAME}
      ELASTICSEARCH_NODE_NAME: ${ELASTICSEARCH_NODE_NAME}
      ELASTICSEARCH_DISCOVERY_SEEDS: ${ELASTICSEARCH_DISCOVERY_SEEDS}
      ELASTICSEARCH_INIT_MASTER_NODE: ${ELASTICSEARCH_INIT_MASTER_NODE}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    networks:
      - localdev
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
